name: EasyTier Core (Linux x86_64 Only)

on:
  push:
    branches: ["main", "develop"]
  workflow_dispatch: # 支持手动点击运行

env:
  CARGO_TERM_COLOR: always

jobs:
  # 第一阶段：编译前端网页
  build_web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Build Dashboard
        run: |
          pnpm -r install
          pnpm -r --filter "./easytier-web/*" build
      - name: Upload Web Dist
        uses: actions/upload-artifact@v4
        with:
          name: web-dist
          path: easytier-web/frontend/dist/*

  # 第二阶段：编译 Rust 程序
  build_linux:
    needs: build_web
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # 下载刚才编译好的前端网页
      - name: Download web dist
        uses: actions/download-artifact@v4
        with:
          name: web-dist
          path: easytier-web/frontend/dist/

      # 安装基础编译环境
      - name: Setup environment
        run: |
          sudo apt update && sudo apt install -y musl-tools protobuf-compiler libprotobuf-dev clang libclang-dev

      - name: Setup Rust
        run: |
          rustup target add x86_64-unknown-linux-musl

      - uses: Swatinem/rust-cache@v2

      # 正式编译
      - name: Build EasyTier
        run: |
          # 编译带网页嵌入的版本
          cargo build --release --target x86_64-unknown-linux-musl --package=easytier-web --features=embed
          # 编译核心程序 (使用 jemalloc)
          cargo build --release --target x86_64-unknown-linux-musl --package=easytier --features=jemalloc

      # 上传最终的二进制文件
      - name: Archive
        uses: actions/upload-artifact@v4
        with:
          name: easytier-linux-x86_64
          path: |
            target/x86_64-unknown-linux-musl/release/easytier-core
            target/x86_64-unknown-linux-musl/release/easytier-cli
